Folspringb 60
folio-org/folio-sample-modules pull request #32
Opened 2022-09-01 07:28 UTC by nirmalr-shah

mod-spring-template: Liquibase configuration implementation

2022-09-02 05:23 UTC, arin-epm approved these changes

2022-09-02 06:11 UTC, gurleenkaurbp approved these changes

2022-09-05 11:38 UTC, TarasSpashchenko requested changes
please have a look how liquibase configured for one of the existing production modules based on the folio-spring-base.
Here we must follow the same approach.

2022-09-06 04:07 UTC, nirmalr-shah commented
> please have a look how liquibase configured for one of the existing production modules based on the folio-spring-base. Here we must follow the same approach.

Done. Requesting your review!!

2022-09-06 05:27 UTC, arin-epm approved these changes

2022-09-13 07:19 UTC, gurleenkaurbp approved these changes

2022-09-13 11:15 UTC, nirmalr-shah commented
> please have a look how liquibase configured for one of the existing production modules based on the folio-spring-base. Here we must follow the same approach.

Done

2022-09-13 11:51 UTC, arin-epm approved these changes

2022-09-13 12:01 UTC, merged