[FOLSPRINGB-97] 1. upgrade spring boot 2 to spring boot 3 2. related …
folio-org/folio-sample-modules pull request #42
Opened 2023-05-05 09:12 UTC by Arghya22

https://issues.folio.org/browse/FOLSPRINGB-97

##Purpose 
1. Upgrade postgresql and snakeyaml 

##Approach 
1. As per description upgrade spring boot 2 -> 3 
2. In order to upgrade to spring boot version 3 , additional changes added for compatibility

2023-05-05 17:26 UTC, ncovercash requested changes
Everything else looks good!

2023-05-05 17:26 UTC, ncovercash commented on mod-spring-petstore/src/main/java/org/folio/petstore/client/config/PetStoreFeignClientConfig.java
> -  @Bean
Why the change in indentation?

2023-05-06 09:02 UTC, Arghya22 commented on mod-spring-petstore/src/main/java/org/folio/petstore/client/config/PetStoreFeignClientConfig.java
> -  @Bean
fixed

2023-05-07 03:21 UTC, ncovercash approved these changes
LGTM

2023-05-08 05:27 UTC, pavankumar181 approved these changes

2023-05-08 06:47 UTC, gurleenkaurbp approved these changes

2023-05-08 07:39 UTC, Vignesh-kalyanasundaram approved these changes

2023-05-08 10:35 UTC, merged